title: Blog of Kerem
email: keremab61@gmail.com
description: Technology, coding and philosophy
author: M3R3K
baseurl: ""
url: "https://m3r3k.github.io"

# Social Profiles
twitter_username:
github_username: M3R3K
facebook_username:
instagram_username: keremfive
linkedin_username: kabdullahoglu

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
